version: '3.1'
services:
  web:
    build: .
    ports:
      - "80:3000"
    container_name: triplanner-app-container

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=triplanner
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'