version: '3.1'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    container_name: triplanner-app-container

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=triplanner
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'

  # mongo:
  #   image: mongo
  #   container_name: mongo-container
  #   ports:
  #     - '27017:27017'

  # redis:
  #   image: redis
  #   container_name: redis-container
  #   command: redis-server --protected-mode no
  #   ports:
  #     - '6379:6379'

  # zookeeper:
  #   image: 'bitnami/zookeeper:latest'
  #   ports:
  #     - '2181:2181'
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  # kafka:
  #   image: 'bitnami/kafka:latest'
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - zookeeper