export enum STAY_TYPE {
    HOTEL_ROOM = 'HOTEL_ROOM',
}

export enum HOTEL_ROOM_TYPE {
    APARTMENT = 'APARTMENT',
    BALCONY = 'BALCONY',
    BDR = 'BDR',
    BUSINESS = 'BUSINESS',
    CONNECTED_ROOMS = 'CONNECTED_ROOMS',
    DE_LUXE = 'DE_LUXE',
    DUPLEX = 'DUPLEX',
    EXTRA_BED = 'EXTRA_BED',
    KING_SIZE = 'KING_SIZE',
    FAMILY_ROOM = 'FAMILY_ROOM',
}