export enum USER_STATUS {
	UNAPPROVED = 'UNAPPROVED',
	APPROVED = 'APPROVED',
	ONSITE = 'ONSITE',
	BLOCKED = 'BLOCKED',
	DELETED = 'DELETED',
}
export enum USER_ROLES {
	ADMIN = 'ADMIN',
	MODERATOR = 'MODERATOR',
	WRITER = 'WRITER',
}